// ============================================================
// UNIFIED NLP ENGINE — Combines All 3 Engines
// ============================================================
// This engine internally uses:
// 1. Rule-Based parsing for structured data extraction
// 2. TF-IDF for keyword extraction and domain classification
// 3. Pattern-Based NLP for action verbs, quantifiers, role detection
//
// The final summary is generated by combining insights from all three.

import type { ResumeFormData, ResumeOutput, SkillCategory } from '../types';
import {
  parseSkills,
  parseEducation,
  parseExperience,
  parseProjects,
  parseCertifications,
  parseRoles,
  parseActivities,
  parseAchievements,
  parseReferences,
} from './ruleBasedEngine';

// ============================================================
// STOP WORDS (shared)
// ============================================================
const STOP_WORDS = new Set([
  'i','me','my','myself','we','our','ours','ourselves','you','your','yours',
  'yourself','yourselves','he','him','his','himself','she','her','hers',
  'herself','it','its','itself','they','them','their','theirs','themselves',
  'what','which','who','whom','this','that','these','those','am','is','are',
  'was','were','be','been','being','have','has','had','having','do','does',
  'did','doing','a','an','the','and','but','if','or','because','as','until',
  'while','of','at','by','for','with','about','against','between','through',
  'during','before','after','above','below','to','from','up','down','in',
  'out','on','off','over','under','again','further','then','once','here',
  'there','when','where','why','how','all','both','each','few','more','most',
  'other','some','such','no','nor','not','only','own','same','so','than',
  'too','very','s','t','can','will','just','don','should','now','also',
  'used','using','worked','work','working','experience','project','projects',
  'developed','built','created','etc','including','like','well','use','good',
]);

// ============================================================
// TF-IDF COMPONENTS
// ============================================================
const DOMAIN_MAP: Record<string, string[]> = {
  'Machine Learning & AI': ['python','ml','machine','learning','tensorflow','pytorch','keras','deep','neural','network','ai','artificial','intelligence','nlp','natural','language','processing','sklearn','scikit','pandas','numpy','data','science','model','classification','regression','clustering'],
  'Web Development': ['react','angular','vue','javascript','typescript','html','css','node','express','django','flask','frontend','backend','fullstack','api','rest','graphql','tailwind','bootstrap','nextjs','next','webpack','vite'],
  'Mobile Development': ['android','ios','flutter','react-native','kotlin','swift','mobile','app'],
  'Cloud & DevOps': ['aws','azure','gcp','google','cloud','docker','kubernetes','ci','cd','jenkins','devops','terraform','ansible'],
  'Database & Backend': ['sql','mysql','postgresql','mongodb','redis','firebase','supabase','database','nosql','orm'],
  'Systems & Low-Level': ['c','c++','cpp','java','rust','go','golang','system','embedded','linux','os','operating'],
  'Cybersecurity': ['security','cyber','penetration','testing','ethical','hacking','firewall','encryption','vulnerability'],
};

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-zA-Z0-9\s+#-]/g, ' ')
    .split(/\s+/)
    .filter(t => t.length > 1 && !STOP_WORDS.has(t));
}

function computeTF(tokens: string[]): Map<string, number> {
  const freq = new Map<string, number>();
  const total = tokens.length || 1;
  for (const t of tokens) freq.set(t, (freq.get(t) || 0) + 1);
  const tf = new Map<string, number>();
  for (const [term, count] of freq) tf.set(term, count / total);
  return tf;
}

function computeIDF(documents: string[][]): Map<string, number> {
  const N = documents.length;
  const df = new Map<string, number>();
  for (const doc of documents) {
    const unique = new Set(doc);
    for (const t of unique) df.set(t, (df.get(t) || 0) + 1);
  }
  const idf = new Map<string, number>();
  for (const [term, count] of df) {
    idf.set(term, Math.log((N + 1) / (count + 1)) + 1);
  }
  return idf;
}

function computeTFIDF(tf: Map<string, number>, idf: Map<string, number>): Map<string, number> {
  const tfidf = new Map<string, number>();
  for (const [term, tfScore] of tf) {
    tfidf.set(term, tfScore * (idf.get(term) || 1));
  }
  return tfidf;
}

function extractTopKeywords(tfidf: Map<string, number>, n = 15): string[] {
  return Array.from(tfidf.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([term]) => term);
}

function classifyDomains(keywords: string[]): string[] {
  const scores = new Map<string, number>();
  for (const kw of keywords) {
    for (const [domain, domainKws] of Object.entries(DOMAIN_MAP)) {
      if (domainKws.includes(kw)) scores.set(domain, (scores.get(domain) || 0) + 1);
    }
  }
  return Array.from(scores.entries()).sort((a, b) => b[1] - a[1]).map(([d]) => d);
}

// ============================================================
// PATTERN-BASED COMPONENTS
// ============================================================
const ACTION_VERBS = new Set([
  'developed','built','created','designed','implemented','managed',
  'led','organized','analyzed','improved','optimized','deployed',
  'maintained','architected','integrated','automated','tested',
  'debugged','collaborated','contributed','launched','published',
  'trained','mentored','coordinated','engineered','researched',
  'streamlined','configured','monitored','resolved','delivered',
  'established','spearheaded','initiated','executed','facilitated',
]);

const TECH_TERM_PATTERN = /\b(API|REST|GraphQL|SQL|NoSQL|CI\/CD|AWS|GCP|Azure|Docker|Kubernetes|Git|GitHub|Linux|Agile|Scrum|MVP|SaaS|SDK|IDE|OOP|MVC|MERN|MEAN|LAMP)\b/gi;
const QUANTIFIER_PATTERN = /(\d+[+%]?)\s*(years?|months?|projects?|users?|clients?|team|members?|apps?|applications?|websites?|systems?)/gi;

function extractActionVerbs(text: string): string[] {
  const words = text.toLowerCase().split(/\s+/);
  return [...new Set(words.filter(w => ACTION_VERBS.has(w)))];
}

function extractQuantifiers(text: string): string[] {
  const matches: string[] = [];
  const regex = new RegExp(QUANTIFIER_PATTERN.source, 'gi');
  let match;
  while ((match = regex.exec(text)) !== null) matches.push(match[0]);
  return matches;
}

function extractTechTerms(text: string): string[] {
  const matches: string[] = [];
  const regex = new RegExp(TECH_TERM_PATTERN.source, 'gi');
  let match;
  while ((match = regex.exec(text)) !== null) matches.push(match[0].toUpperCase());
  return [...new Set(matches)];
}

function extractBigrams(text: string): string[] {
  const stopWords = new Set(['the','and','for','with','has','was','are','this','that','from','but','not','its']);
  const words = text.toLowerCase().replace(/[^a-zA-Z0-9\s]/g, '').split(/\s+/).filter(w => w.length > 2);
  const bigrams: string[] = [];
  for (let i = 0; i < words.length - 1; i++) {
    if (!stopWords.has(words[i]) && !stopWords.has(words[i + 1])) {
      bigrams.push(`${words[i]} ${words[i + 1]}`);
    }
  }
  return bigrams;
}

function detectRole(allText: string): string {
  const text = allText.toLowerCase();
  const rolePatterns: [string, string[]][] = [
    ['Full-Stack Developer', ['fullstack','full-stack','full stack','frontend','backend','react','node','mern','mean']],
    ['Frontend Developer', ['frontend','front-end','react','angular','vue','css','html','ui','ux']],
    ['Backend Developer', ['backend','back-end','node','express','django','flask','api','server']],
    ['Data Scientist', ['data science','machine learning','ml','pandas','numpy','sklearn','statistics','analysis']],
    ['ML Engineer', ['tensorflow','pytorch','deep learning','neural network','model training','ai']],
    ['Mobile Developer', ['android','ios','flutter','react native','mobile','kotlin','swift']],
    ['DevOps Engineer', ['devops','docker','kubernetes','ci/cd','jenkins','terraform','ansible']],
    ['Cloud Engineer', ['aws','azure','gcp','cloud','lambda','ec2','s3']],
    ['Software Engineer', ['software','engineer','developer','programming','coding','java','python','c++']],
    ['Cybersecurity Analyst', ['security','cyber','penetration','vulnerability','firewall','encryption']],
  ];
  let bestRole = 'Software Professional';
  let bestScore = 0;
  for (const [role, kws] of rolePatterns) {
    const score = kws.filter(k => text.includes(k)).length;
    if (score > bestScore) { bestScore = score; bestRole = role; }
  }
  return bestRole;
}

function detectExperienceLevel(text: string): string {
  const yearMatch = text.match(/(\d+)\+?\s*years?/i);
  if (yearMatch) {
    const years = parseInt(yearMatch[1]);
    if (years >= 5) return 'senior';
    if (years >= 2) return 'mid-level';
    return 'junior';
  }
  const studentWords = ['student','pursuing','currently studying','fresher','graduate','undergraduate','intern'];
  if (studentWords.some(w => text.toLowerCase().includes(w))) return 'entry-level';
  return 'aspiring';
}

// ============================================================
// UNIFIED SUMMARY GENERATION
// ============================================================
function generateUnifiedSummary(
  data: ResumeFormData,
  skills: SkillCategory[],
  topKeywords: string[],
  domains: string[],
  actionVerbs: string[],
  quantifiers: string[],
  techTerms: string[],
  bigrams: string[],
  role: string,
  level: string,
): string {
  // If user provided career objective, use it as base and enhance
  if (data.careerObjective.trim()) {
    const base = data.careerObjective.trim();
    // Enhance with detected keywords if not already present
    const enhancements: string[] = [];
    if (topKeywords.length > 0 && !base.toLowerCase().includes(topKeywords[0])) {
      enhancements.push(`Key competencies: ${topKeywords.slice(0, 4).join(', ')}.`);
    }
    return enhancements.length > 0 ? `${base} ${enhancements.join(' ')}` : base;
  }

  // Build summary using all three engine insights
  const levelMap: Record<string, string> = {
    senior: 'Seasoned and accomplished',
    'mid-level': 'Experienced and skilled',
    junior: 'Enthusiastic and growing',
    'entry-level': 'Motivated and eager',
    aspiring: 'Passionate and dedicated',
  };

  const parts: string[] = [];

  // Opening with role and level (Pattern-Based)
  parts.push(`${data.fullName} is a ${levelMap[level] || 'dedicated'} ${role}`);

  // Add domain context (TF-IDF)
  if (domains.length > 0) {
    parts[0] += ` specializing in ${domains.slice(0, 2).join(' and ')}.`;
  } else {
    parts[0] += '.';
  }

  // Add quantified experience (Pattern-Based)
  if (quantifiers.length > 0) {
    parts.push(`With ${quantifiers[0]} of hands-on experience,`);
  }

  // Add action verbs accomplishments (Pattern-Based)
  if (actionVerbs.length >= 2) {
    parts.push(`has successfully ${actionVerbs.slice(0, 3).join(', ')} various technical solutions.`);
  }

  // Add skills context (Rule-Based)
  const allSkills = skills.flatMap(s => s.items);
  if (allSkills.length > 0) {
    parts.push(`Proficient in ${allSkills.slice(0, 5).join(', ')}.`);
  }

  // Add tech terms (Pattern-Based)
  if (techTerms.length > 0) {
    parts.push(`Experienced with industry standards including ${techTerms.slice(0, 4).join(', ')}.`);
  }

  // Add bigram expertise areas (Pattern-Based)
  if (bigrams.length > 0) {
    parts.push(`Key areas of expertise include ${bigrams.slice(0, 3).join(', ')}.`);
  }

  // Add top keywords from TF-IDF
  if (topKeywords.length > 0 && domains.length === 0) {
    parts.push(`Core technical competencies: ${topKeywords.slice(0, 5).join(', ')}.`);
  }

  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

// ============================================================
// MAIN UNIFIED ENGINE FUNCTION
// ============================================================
export function generateWithUnifiedEngine(data: ResumeFormData): ResumeOutput {
  console.log('\n' + '='.repeat(60));
  console.log('[Unified NLP Engine] Starting processing...');
  console.log('='.repeat(60));

  // ---- STEP 1: Rule-Based Parsing ----
  console.log('\n[Step 1] Rule-Based Parsing...');
  const skills = parseSkills(data.skills);
  const education = parseEducation(data.education);
  const experience = parseExperience(data.experience);
  const projects = parseProjects(data.projects);
  const certifications = parseCertifications(data.certifications);
  const roles = parseRoles(data.roles);
  const activities = parseActivities(data.activities);
  const achievements = parseAchievements(data.achievements);
  const references = parseReferences(data.references);

  console.log('  → Parsed Skills:', skills.length, 'categories');
  console.log('  → Parsed Education:', education.length, 'entries');
  console.log('  → Parsed Experience:', experience.length, 'entries');
  console.log('  → Parsed Projects:', projects.length, 'entries');

  // ---- STEP 2: TF-IDF Analysis ----
  console.log('\n[Step 2] TF-IDF Keyword Extraction...');
  const documents = [
    tokenize(data.skills),
    tokenize(data.experience),
    tokenize(data.projects),
    tokenize(data.education),
    tokenize(data.careerObjective),
    tokenize(data.certifications),
    tokenize(data.achievements),
  ].filter(doc => doc.length > 0);

  const allTokens = documents.flat();
  const tf = computeTF(allTokens);
  const idf = computeIDF(documents);
  const tfidf = computeTFIDF(tf, idf);
  const topKeywords = extractTopKeywords(tfidf, 15);
  const domains = classifyDomains(topKeywords);

  console.log('  → Total tokens:', allTokens.length);
  console.log('  → Top Keywords:', topKeywords.slice(0, 8).join(', '));
  console.log('  → Detected Domains:', domains.slice(0, 3).join(', ') || 'General');

  // ---- STEP 3: Pattern-Based Analysis ----
  console.log('\n[Step 3] Pattern-Based NLP Analysis...');
  const allText = [data.skills, data.experience, data.projects, data.education, data.certifications, data.roles].join(' ');
  const actionVerbs = extractActionVerbs(allText);
  const quantifiers = extractQuantifiers(allText);
  const techTerms = extractTechTerms(allText);
  const bigrams = extractBigrams(data.skills + ' ' + data.projects);
  const role = detectRole(allText);
  const level = detectExperienceLevel(allText);

  console.log('  → Action Verbs:', actionVerbs.slice(0, 5).join(', '));
  console.log('  → Quantifiers:', quantifiers.slice(0, 3).join(', ') || 'None');
  console.log('  → Tech Terms:', techTerms.slice(0, 5).join(', '));
  console.log('  → Bigrams:', bigrams.slice(0, 3).join(', '));
  console.log('  → Detected Role:', role);
  console.log('  → Experience Level:', level);

  // ---- STEP 4: Generate Unified Summary ----
  console.log('\n[Step 4] Generating Unified Summary...');
  const summary = generateUnifiedSummary(
    data, skills, topKeywords, domains,
    actionVerbs, quantifiers, techTerms, bigrams,
    role, level
  );
  console.log('  → Summary:', summary);

  // ---- STEP 5: Build Output ----
  console.log('\n[Step 5] Building final output...');
  const output: ResumeOutput = {
    name: data.fullName,
    email: data.email,
    phone: data.phone,
    address: data.address,
    linkedIn: data.linkedIn,
    github: data.github,
    portfolio: data.portfolio,
    codingProfiles: data.codingProfiles,
    tagline: data.tagline,
    summary,
    skills,
    education,
    experience,
    projects,
    certifications,
    roles,
    activities,
    achievements,
    references,
  };

  console.log('\n' + '='.repeat(60));
  console.log('[Unified NLP Engine] Processing complete!');
  console.log('='.repeat(60));

  return output;
}
